---
- name: Include packages for RHEL Based flavors
  include_tasks: redhat.yml
  when:
    ansible_os_family == "RedHat"

- name: Include packages for Debian Based flavors
  include_tasks: debian.yml
  when:
    ansible_os_family == "Debian"
