---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: packages-centos
    image: centos:7
    groups:
      - centos
  - name: package-debian
    image: debian:latest
    groups:
      - debian
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["403"]
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
